version: '3.7'

services:
  mtg-inventory-system:
    container_name: mtg-inventory-system
    build:
      context: .
      dockerfile: docker/inventory-system/Dockerfile
    volumes:
      - "./src/mtg_inventory_system/:/src/:delegated"
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      mtg-postgres:
        condition: service_healthy
        restart: true
        required: true

  mtg-postgres:
    container_name: mtg-postgres
    image: postgres:14.5-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3

#  mtg-ai-card-detector:
#    container_name: mtg-card-detector
#    env_file:
#      - src/mtg_inventory_system/mtg_inventory_system/.env
#    build:
#      context: .
#      dockerfile: docker/mtg-card-detector/Dockerfile
#      target: mtg-card-detector
#    volumes:
#      - "./container/card_image_detector/:/src/:delegated"
