version: '3.7'

services:
  mtg-ai-card-detector:
    container_name: mtg-ai-card-detector
    build:
      context: .
      dockerfile: docker/ai-card-detector/Dockerfile
      target: mtg-ai-card-detector
    volumes:
      - "./:/src:delegated"